### ISSUE TITLE
Unwanted gray border around top and left of calendar

### ISSUE THREAD

**Issue by synthead** [pyxelr/Dark_Google_Calendar#13]
There is an unwanted gray border around top and left of calendar.  This started appearing approximately since the second week of March, 2021.

![image](https://user-images.githubusercontent.com/820984/111484616-2a501b80-86f3-11eb-8129-be81ca0a23f1.png)

**Comment by pyxelr** [comment]
Are you running version 2.7.5? I just checked it with this newest version and there is no such issue in any view (Day, Week, 4 days).

**Comment by synthead** [comment]
I should have mentioned!  Yes, this is with version 2.7.5.  I'm using Firefox 86.0.1 on Linux, if it matters.

**Comment by synthead** [comment]
Interesting!  On further inspection, they appear to be scroll bars.  When I make the window smaller, you can see the scrollbar appear:

![image](https://user-images.githubusercontent.com/820984/111681011-0fa7a080-87e0-11eb-9789-50d19e8c0bf5.png)

**Comment by pyxelr** [comment]
Hmm, in my case it appears in a bit different order (Chrome on Windows 10):

![2021-03-18_23-28-21](https://user-images.githubusercontent.com/30161753/111705987-d0aa3700-8841-11eb-9a17-a184a701022c.png)

**Comment by synthead** [comment]
For whatever reason, this issue isn't present on my calendar anymore.  I'm going to mark this as closed for now, but please feel free to reopen if you see it :+1:

**Comment by synthead** [comment]
Strange, this issue is visible today 🤔

**Comment by synthead** [comment]
And it's gone :shrug:  I wish I had a better reason why this happened.  I'm on Firefox 88.0.1 now, if it matters :eyes:
