### ISSUE TITLE
After restarting the browser, the first time an event is created, the dark theme is disabled

### ISSUE THREAD

**Issue by Korb** [pyxelr/Dark_Google_Calendar#14]
Then the theme is activated again, and then does not turn off. Until the browser is restarted.

Mozilla Firefox 106.0.1 (64-bit)
Stylus 1.5.26 (30 August 2022)
Google Translate Dark 1.3.1
Microsoft Windows 10.0.19045.2130

**Comment by pyxelr** [comment]
Does this issue also happen to you with other themes, or even themes on the other websites?
Could you try reinstalling the theme with Stylus to see if it helps?

**Comment by Korb** [comment]
> Does this issue also happen to you with other themes, or even themes on the other websites? Could you try reinstalling the theme with Stylus to see if it helps?

I haven't seen this effect on other sites. I currently have the following styles set:

1. Dark Docs 2022.10.20
2. Dark Google Calendar 2.7.8
3. Fandom Cleanup
4. Fandom Remove Background Colour 1.2.0
5. Firefox PNG Transparen­cy Fix 1.0
6. Google Translate Dark 1.3.1
7. Instagram Super
8. Messenger Dark 1.2.15
9. RU AdList CSS Fixes 0.20221021.1419
10. Telegram Käfer 1.0.1
11. Wikipedia Dark 3.6.0
12. Yandex.Disk Dark MOD 20220121.00.18

Of these, only the following are active on calendar.google.com — "Dark Google Calendar" and "Firefox PNG Transparen­cy Fix".

>  Could you try reinstalling the theme with Stylus to see if it helps?

I've reinstalled your style and will be watching my computers over the next few days (I use the Mozilla browser profile that is synchronized across multiple computers).

**Comment by Korb** [comment]
The problem doesn't seem to recur anymore. I will close the issue. If the problem comes back, we'll get back to it.
