### ISSUE TITLE
Title, date and time on the event editing screen are displayed as blocked from changing

### ISSUE THREAD

**Issue by Korb** [pyxelr/Dark_Google_Calendar#15]
No style:
![2023-01-06_10-38-01](https://user-images.githubusercontent.com/3509797/210953465-813495bc-9549-4a23-a4ea-8d5779b0ff0b.png)
With style:
![2023-01-06_10-38-17](https://user-images.githubusercontent.com/3509797/210953467-fe272799-6bf7-4f76-b2ca-145fd9ba6857.png)
Mozilla Firefox 109.0b8 (64-bit), Stylus 1.5.26 (1 September 2022).

**Comment by pyxelr** [comment]
Thanks for reporting. It should be fixed now with the latest style version.
