### ISSUE TITLE
Grayed out text for Calendar Event Name and Participants

### ISSUE THREAD

**Issue by remaindeer** [pyxelr/Dark_Google_Calendar#16]
Hi, it seems the event name and the participants are grayed out and this was a bit jarring for me, as if the intended meaning was that the event was not confirmed or I had no edit rights. Could you take a look at this? Thanks

![image](https://user-images.githubusercontent.com/402154/226328897-9c972d73-1cbc-41a2-9d27-242c37e3be25.png)

**Comment by pyxelr** [comment]
Hi @remaindeer,

Thank you for reporting it. You are right, it did not look great.
It should be fixed now once you update the theme.

**Comment by pyxelr** [comment]
Hi @remaindeer,

Thank you for reporting it. You are right, it did not look great.
It should be fixed now once you update the theme to `2.7.13`.
