### ISSUE TITLE
clarify license

### ISSUE THREAD

**Issue by cardi** [pyxelr/Dark_Google_Calendar#2]
Thank you for creating and maintaining this!

The license In [Style.css](https://github.com/pyxelr/Dark_Google_Calendar/blob/eedd9202c462dce8d0293bd3a956b22b5e357e0a/Style.css) is [`cc-by-sa-4.0`](https://creativecommons.org/licenses/by-sa/4.0/), but on [userstyles.org](https://userstyles.org/styles/143026/dark-google-calendar-2019), the license is [`cc0-1.0`](https://creativecommons.org/publicdomain/zero/1.0/).

Could you clarify or update the license on the stylesheet?

Thanks, again.

**Comment by pyxelr** [comment]
Well noticed, @cardi.
I updated the license of this repository to [MIT](https://opensource.org/licenses/MIT), as well as the license of the upload on [userstyles.org](https://userstyles.org/styles/143026/dark-google-calendar-2019) to [`CC BY 4.0`](https://creativecommons.org/licenses/by/4.0/). Currently, both hostings seem to be matching their license terms.

Sorry for the late reply, but my notifications in the repository were turned off.

**Comment by cardi** [comment]
Thanks, @pyxelr!
