### ISSUE TITLE
White top border on entries

### ISSUE THREAD

**Issue by devenv** [pyxelr/Dark_Google_Calendar#20]
Not sure why, adding this removed it:
```
    .EfQccc.EiZ8Dd:after {
        border-top: none;
    }
```
<img width="213" alt="image" src="https://github.com/pyxelr/dark-google-calendar/assets/304936/33a0a3bb-af3a-4e6f-964e-e777d102c632">

**Comment by pyxelr** [comment]
Unfortunately, I cannot replicate your issue with the white border on entries in the daily calendar. Could you double-check if this happens when you try a different browser or a device?

**Comment by devenv** [comment]
Probably something on my side
