### ISSUE TITLE
Publish as UserCSS

### ISSUE THREAD

**Issue by outfrost** [pyxelr/Dark_Google_Calendar#3]
Hi,
I love the work you're doing maintaining this style. Thank you!
If I may, I have a small request. Could you maybe, apart from hosting on Userstyles, publish the style as a [UserCSS](https://github.com/openstyles/stylus/wiki/UserCSS-authors)? It would allow lightning quick installation, and automatic updates, straight from master on GitHub. Basically it eliminates the need to use Userstyles.org for those of us who don't want to, and adds an extra feature on top.
I can make a quick fork and submit PR, if you like.

**Comment by pyxelr** [comment]
Thank you, @outfrost.
I've just added the UserCSS support inside the repository, as well as updated the repository description accordingly.

Sorry for the late reply, but my notifications in the repository were turned off.

**Comment by outfrost** [comment]
Awesome, thanks! And no worries at all ^^
