### ISSUE TITLE
Cannot update from Stylus: "Invalid version number. The value doesn't match SemVer pattern: 2.60.8</span></td>"

### ISSUE THREAD

**Issue by synthead** [pyxelr/Dark_Google_Calendar#6]
In Stylus, if I attempt to update, I get this message:

![image](https://user-images.githubusercontent.com/820984/79494796-72912600-7fd8-11ea-9cae-f594ce829e1c.png)

```
Invalid version number. The value doesn't match SemVer pattern: 2.60.8</span></td>
```

**Comment by pyxelr** [comment]
Thank you for reporting.

I tried various ways of fixing the issue, and no change in the metadata of the  .user.css file was able to resolve this problem.

In the end, I've created a new .user.css file that doesn't seem to reproduce this problem, and as I already checked with sample commits, Stylus has no troubles with updating it. Therefore, please reinstall the .user.css file on your side.
