### ISSUE TITLE
Avatars in contact tooltips that appear from the "Add guests" list has inverted colors

### ISSUE THREAD

**Issue by synthead** [pyxelr/Dark_Google_Calendar#8]
When hovering over an avatar from the guest list, a tooltip appears that contains said avatar, but with inverted colors:

![image](https://user-images.githubusercontent.com/820984/89588333-4bb16680-d7f8-11ea-85d4-3ed823ea15e5.png)

### Steps to reproduce:

1. Start creating a calendar event.
2. Click on "Add guests" in the form.
3. Type a contact name and add them from the "Add guests" field.
4. Hover the cursor over their avatar.
5. Observe that a tooltip appears, and that the avatar colors are inverted.

**Comment by pyxelr** [comment]
Thanks for reporting, @synthead.
I have just fixed this issue in the [newest commit](https://github.com/pyxelr/Dark_Google_Calendar/commit/071c2b0f58e2549f0bfa156cbedb9cfa4fd392b8).
